# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1-stretch

    working_directory: ~/repo

    steps:
      - checkout

      # TODO: cache packages dependencies too
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-root-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-root-dependencies-

      - run:
          name: "Install lerna"
          command: sudo yarn global add lerna@3.10

      - run:
          name: "Install packages"
          command: yarn bootstrap

      - save_cache:
          paths:
            - node_modules
          key: v1-root-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: "Run tests"
          command: yarn test

      - run:
          name: "Test CLI bin files"
          command: |
            ./packages/cli/bin/supermodel --version
            ./packages/cli/bin/supermodel import --version
            ./packages/cli/bin/supermodel install --version
            ./packages/cli/bin/supermodel login --version
            ./packages/cli/bin/supermodel model --version
            ./packages/cli/bin/supermodel pull --version
            ./packages/cli/bin/supermodel push --version
            ./packages/cli/bin/supermodel schema --version
            ./packages/cli/bin/supermodel signup --version
            ./packages/cli/bin/supermodel validate --version
            ./packages/cli/bin/supermodel whoami --version